protected/controllers/AppController.php
<?php
class AppController extends BaseController
{

    public function filters()
    {
        return array(
            'accessControl',
        );
    }

	public function actionIndex(){

        $data = Applib::model()->findAll();
        $items = array();
        foreach ($data as $app) {
            $item = $app->attributes;
            if($app->file){
                $url = 'http://'.$_SERVER['HTTP_HOST'].'/'.Yii::app()->params['config']['upload_relative'].'/'.$app->project->platform.'/';
                if($app->project->platform == 'android'){
                    $item['download_url'] = $url.$app->file->save_name.'.apk';
                }else{
                    $item['download_url'] = $url.$app->file->save_name.'.ipa';
                }
                $item['md5'] = $app->file->md5;
            }else{
                $item['download_url'] = '';
                $item['md5'] = '';
            }
            $item['project'] = $app->project->project;
            $item['platform'] = $app->project->platform;
            $items[] = $item;
        }
        $this->render('select',array("data"=>$items,'root'=>Yii::app()->params['config']['root']));
	}

    //添加版本
    public function actionAdd(){

        if(isset($_POST['submit'])&&$_POST['submit']==='提交'){

            $project = Project::model()->find('identifier=:identifier',array(':identifier'=>$_POST['identifier']));
            if($project){

                $now = date("Y-m-d H:i:s");

                $applib = new Applib;
                $applib->identifier = $_POST['identifier'];
                $applib->version = $_POST['version'];
                $applib->release_note = $_POST['release_note'];
                $applib->update_time = $now;
                $return = $applib->save();
                if($return){
                    $inputName = 'uploadfile';
                    
                    $config = Yii::app()->params['config'];
                    $prefix = $config['upload_absolute'];
                    $path = '/'.$project->platform.'/';

                    $pathInfo = pathinfo($_FILES[$inputName]['name']);
                    $md5Name = md5(uniqid(mt_rand(), true));
                    $filename = $md5Name . '.' . strtolower($pathInfo["extension"]);
                    $src = $prefix . $path . $filename;

                    if($project->platform == 'android'){
                        $file_limit = array(
                                'extension'=>array('apk')
                            );
                    }else{
                        $file_limit = array(
                                'extension'=>array('ipa')
                            );
                    }
                    $file = new uploadfile($inputName,$src,$file_limit);
                    $ret = $file->save();

                    if($ret['error']){
                        echo $ret['error'];
                    }else{
                        $file = new File;
                        $file->name = $_FILES[$inputName]['name'];
                        $file->save_name = $md5Name;
                        $file->type = $_FILES[$inputName]['type'];
                        $file->size = $_FILES[$inputName]['size'];
                        $file->md5 = md5_file($src);
                        $file->upload_time = $now;
                        $file->lib_id = $applib->id ;
                        $return = $file->save();
                        if($return){
                            if($project->platform == 'iphone'|| $project->platform == 'ipad'){

                                $ipa_dir = $prefix.$path;
                                $ipa_url = 'http://'.$_SERVER['HTTP_HOST'].'/'.$config['upload_relative'].$path;
                                $str = file_get_contents($ipa_dir.$project['project'].'.plist');

                                file_put_contents($prefix . $path . $md5Name . '.plist', str_replace('{ipa_url}',$ipa_url.$md5Name.'.ipa',$str)) ;
                            }
                            // echo '成功';
                            $this->redirect(array('app/')); 
                        }else{
                            echo '文件信息保存失败';
                        }
                    }
                }else{
                    echo '版本信保存失败';
                }
            }else{
                echo 'error identifier!';
            }
        }else{
            $this->render('add');
        }
    }

    // http://api/app/info?identifier=62ef9128e9fc7fa9a7bdef8bb5dbfc13  android
    // http://api/app/info?identifier=e16affe6856c04f6008cc9d0cdf28b18  iphone
    public function actionInfo(){
        $app = Applib::model()->find(array(
                'condition'=>'identifier=:identifier',
                'order'=>'sort desc,id desc',
                'params'=>array(':identifier'=>$_GET['identifier'])
            ));
        if($app){
            if($app->file){
                $url = 'http://'.$_SERVER['HTTP_HOST'].'/'.Yii::app()->params['config']['upload_relative'].'/'.$app->project->platform.'/';
                if($app->project->platform == 'android'){
                    $download_url = $url.$app->file->save_name.'.apk';
                }else{
                    $download_url = 'itms-services://?action=download-manifest&url='.$url.$app->file->save_name.'.plist';
                }
                $data = array(
                    'identifier'=>$app->identifier,
                    'version'=>$app->version,
                    'release_note'=>$app->release_note,
                    'download_url'=>$download_url,
                    'md5'=>$app->file->md5
                );
                $return = array('error_code'=>200, 'error_msg'=>'OK', 'data'=>$data);
            }else{
                $return = array('error_code'=>404, 'error_msg'=>'未找到文件');
            }
        }else{
            $return = array('error_code'=>404, 'error_msg'=>'');
        }
        $this->renderJSON($return);
    }

    public function actionDel(){

        $ret = Applib::model()->deleteByPk($_GET['id']);

        $this->redirect(array('app/')); 
        // $this->select('applib');
    }

    public function actionDelall(){
        foreach ($_POST['id'] as &$v) {
            $v = (int)$v;
        }
        $instr = implode(',', $_POST['id']);
        $ret = Applib::model()->deleteAll('id in ('.$instr.')');
        if($ret){
            //成功删除 $ret 条
            echo "OK";
        }else{
            echo "error";
        }
    }

    //更新数据
    public function actionUpd(){
        $data = Applib::model()->findByPk($_POST['id']);
        $data->version = $_POST['version'] ;
        $data->release_note = $_POST['release_note'] ;
        $data->sort = $_POST['sort'] ;
        $data->update_time = date("Y-m-d H:i:s");
        if($data->save()){
            $error_msg = "OK";
        }else{
            $error_msg = "XXX出错！";
        }
        echo $error_msg;
        //$this->select('applib');
    }

    public function actionEdit(){
        $data = Applib::model()->findByPk($_GET['id']);
        // $this->renderJSON($data);
        $this->renderPartial('edit',array('data'=>$data));
    }

    public function accessRules()
    {
        return array(
            array('allow',
                'actions'=>array('index','del','delAll','add','upd','edit'),
                'users'=>array('admin'),
            ),
            array('allow',
                'actions'=>array('index','add','upd','edit'),
                'users'=>array('upload'),
            ),
            array('deny',
                'actions'=>array('index','del','delAll','add','upd','edit'),
            ),
        );
    }

}

protected/views/app/add.php
<div>
    <form action="<?php echo $this->createUrl('app/add') ?>" method="post" enctype="multipart/form-data">
        <ul>
            <li>标识：<input type="text" name="identifier" ></li>
            <li>版本：<input type="text" name="version" ></li>
            <li>文件：<input type="file" name="uploadfile"></li>
            <li>日志：<textarea name="release_note"></textarea></li>
            <li><input type="submit" name="submit" value="提交"></li>
        </ul>
    </form>
</div>

protected/views/app/edit.php
<div>
    <form id="edit">
        <input type="hidden" name="id" value="<?php echo $data['id']; ?>">
        <ul>
            <li>标识：<?php echo $data['identifier']; ?></li>
            <li>版本：<input type="text" name="version" value="<?php echo $data['version']; ?>"></li>
            <li>说明：<textarea name="release_note"><?php echo $data['release_note']; ?>"></textarea></li>
            <li>优先：<input type="text" name="sort" value="<?php echo $data['sort']; ?>"></li>
        </ul>
    </form>
</div>

protected/views/app/select.php
<script type="text/javascript">

	function load(obj){
		
		var dialogId = 'mymodal';
		$.ajax({
            'type': 'POST',
            'url' : $(obj).attr('href'),
            success: function (data) {
                $('#'+dialogId+' div.divForForm').html(data);
                $( '#'+dialogId ).dialog( 'open' );
            },
            dataType: 'html'
        });
	}

	function edit(){
		$.post("<?php echo $this->createUrl('app/upd') ?>", $("#edit").serialize(),function(data){
			if(data == 'OK'){
				$( '#mymodal' ).dialog( 'close' );
				location=location;
				alert('保存成功!');
			}
    	});
	}

	function pagelist(id){
		$('#'+id+' .checkall').click(function(){
			$('#'+id+' .idcheck').each(function(){
				this.checked = true;
			});
		});
		$('#'+id+' .checkother').click(function(){
			$('#'+id+' .idcheck').each(function(){
				this.checked = !this.checked;
			});
		});
		$('#'+id+' .delchecked').click(function(){
			if(confirm("确定要删除选中的记录?")){
				$.post("<?php echo $this->createUrl('app/delall') ?>", $("#"+id+" form").serialize(),function(data){
					if(data == 'OK'){
						location=location;
						alert("删除成功！");
					}
		    	});
			}
		});
	}

	$(function(){

		pagelist('page');

	});
</script>
<?php
$this->beginWidget('zii.widgets.jui.CJuiDialog', array(
    'id'=>'mymodal',
    'options'=>array(
                'title'=>'编辑',
                'width'=>500,
                // 'height'=>500,
                'autoOpen'=>false,
                'resizable'=>false,
                'modal'=>true,
                'overlay'=>array(
                    'backgroundColor'=>'#000',
                    'opacity'=>'0.5'
                    ),
                'buttons'=>array(
                    '保存'=>'js:function(){ edit();}',
                    '取消'=>'js:function(){$(this).dialog("close");}',
                    ),
                ),
            ));
echo '<div class="divForForm">loading....</div>';
$this->endWidget('zii.widgets.jui.CJuiDialog');
?>
<div id="page" class="pagelist">
	<div>
		<span>[<a href="javascript:void(0);" class="checkall">全选</a>] / [<a href="javascript:void(0);" class="checkother">反选</a>]</span>
		<span>　</span>
		<span>[<a href="javascript:void(0);" class="delchecked">批量删除</a>]</span>
		<span style="float:right;"><a href="<?php echo $this->createUrl('app/add') ?>">添加</a></span>
	</div>
	<br>
	<form>
		<table>
			<tr>
				<td>选择</td>
				<td>id</td>
				<td>标识</td>
				<td>项目</td>
				<td>平台</td>
				<td>版本</td>
				<td>说明</td>
				<td>优先</td>
				<td>更新时间</td>
				<td>文件</td>
				<td>操作</td>
			</tr>
			<?php foreach ($data as $v) {

				echo '<tr>';
				echo '<td><input type="checkbox" class="idcheck" name="id[]" value="',$v['id'],'"></td>';
				echo '<td>'.$v['id'].'</td>';
				echo '<td><a href="',$root,'/app/info?identifier=',$v['identifier'],'">',$v['identifier'],'</a></td>';
				echo '<td>'.$v['project'].'</td>';
				echo '<td>'.$v['platform'].'</td>';
				echo '<td>'.$v['version'].'</td>';
				// echo '<td>'.$v['download_url'].'</td>';
				echo '<td>'.$v['release_note'].'</td>';
				echo '<td>'.$v['sort'].'</td>';
				echo '<td>'.$v['update_time'].'</td>';
				echo '<td><a href="',$v['download_url'],'">下载</a> <a href="#" title="',$v['md5'],'">md5</a></td>';
				echo '<td>',CHtml::link('编辑',$this->createUrl('app/edit',array('id'=>$v['id'])),array('onclick'=>'load(this); return false;')),
					' <a href="',$this->createUrl('app/del',array('id'=>$v['id'])),
					'" onclick="return confirm(\'确认删除?\');" >删除</a></td>';
				echo "</tr>";

			}?>
		</table>
	</form>
</div>